server:
  port: 9001
spring:
  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yimoapi
    username: root
    password: abc307680
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848